[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/auth"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/config"
  to = "/.netlify/functions/config"
  status = 200

[[redirects]]
  from = "/generate"
  to = "/.netlify/functions/generate"
  status = 200
